"""add output_urls to codebase_videos

Revision ID: 48578cfeb06a
Revises: f9c5eba03d33
Create Date: 2026-07-09 15:25:04.417172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48578cfeb06a'
down_revision: Union[str, None] = 'f9c5eba03d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (this table already has data) —
    # a NOT NULL column added without one would fail on any existing row.
    op.add_column(
        'codebase_videos',
        sa.Column('output_urls', sa.JSON(), nullable=False, server_default='[]'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codebase_videos', 'output_urls')
    # ### end Alembic commands ###
